FROM ubuntu:18.04 as base

RUN apt-get update && apt-get install  -y \
        libncurses5-dev \
        lib32z1* \
        pkg-config \
        libc6-dev-i386 \
        lib32z1 \
        lib32ncurses5 \
        cmake \
        libncurses5-dev \
        libncursesw5-dev \
        bc \
        xz-utils \
        automake \
        libtool \
        libevdev-dev \
        pkg-config \
        xz-utils \
        python \
        git \
        make \
        gcc \
        g++ \ 
        wget \ 
        cpio \
        unzip \
        rsync \
        flashrom \
        binwalk
